### ISSUE TITLE
Hay que arreglar el estilo y pasarlo a sass

### ISSUE THREAD

**Issue by Amrodalcarin** [MauricioMCavalleriS/ADPR#3]
El estilo esta en plan básico, hay que pasarlo

**Comment by Amrodalcarin** [comment]
Ya modifique un poco el estilo, solo falta pasarlo a sass

**Comment by Amrodalcarin** [comment]
Cree los ficheros traducidos en sass pero no se como hacer que funcionen porque de manera tradicional ya lo intente y peta

**Comment by danielquijada** [comment]
Pasado a sass, sólo falta modificarlo un poco
